apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: {{ .Release.Name }}-kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - name: kafka-broker
          image: {{.Values.kafkaImage.image}}
          imagePullPolicy: {{.Values.kafkaImage.pullPolicy}}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: <ZOOKEEPER-INTERNAL-IP>:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker:9092
            - name: ZOO_ENABLE_AUTH
              value: "yes"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"  
          ports:
            - containerPort: {{.Values.port.kafkaPort}}